#! /bin/sh

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^1' follow=on

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Microsoft-edge desktop='^2' follow=on

bspc rule -a Thunar desktop='^3' follow=on

bspc rule -a neovim desktop='^4' follow=on
bspc rule -a Code desktop='^4' follow=on

bspc rule -a leagueclientux.exe desktop='^5' 
bspc rule -a leagueclient.exe desktop='^5' 
bspc rule -a Zenity desktop='^5'
bspc rule -a zenity desktop='^5'
bspc rule -a Lutris desktop='^5' follow=on

bspc rule -a Spotify desktop='^6' follow=on

bspc rule -a Signal desktop='^7' follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a silos-whatsapp desktop='^7' follow=on

pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/i3/bin/autostart.sh &
bash ~/.config/bspwm/bin/launchbar.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --config ~/.config/i3/picom.conf &
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a "Polybar tray window")
